// src/components/dashboard/LiveAccountsCard.tsx
interface LiveAccount {
  label: string
  value: number
}

interface LiveAccountsCardProps {
  accounts?: LiveAccount[]
  totalBalance?: string
}

export function LiveAccountsCard({
  accounts = [
    { label: 'GFX', value: 70 },
    { label: '10X', value: 45 },
    { label: 'PSN', value: 85 },
  ],
  totalBalance = '$90.254,58',
}: LiveAccountsCardProps) {
  return (
    <div className="relative overflow-hidden bg-white/5 rounded-2xl shadow-[0px_4.64px_23.2px_rgba(0,0,0,0.2),inset_0px_1.16px_0px_1.16px_rgba(255,255,255,0.04)] outline outline-1 outline-offset-[-1.16px] outline-white/5 backdrop-blur-xl h-[12.8125rem] 3xl:h-[16rem]">
      <div className="absolute top-0 left-[10%] right-[10%] h-px divider-glow" aria-hidden="true" />
      <div className="relative z-10 flex flex-col h-full p-4 sm:p-6">
        <div className="flex justify-between items-center mb-2">
          <h3 className="text-card-label text-gfx-neutral-500 font-normal">Live Accounts</h3>
          <div className="px-2.5 py-1.5 bg-teal-700/25 rounded-[20.83px] outline outline-1 outline-offset-[-1px] outline-neutral-700 backdrop-blur-xs inline-flex justify-start items-start gap-1.5">
            <span className="text-white text-xs font-normal leading-5">{totalBalance}</span>
          </div>
        </div>
        <div className="flex flex-row items-center gap-2">
          <p className="text-card-value text-white">{accounts.length}</p>
          <span className="text-card-label text-gfx-neutral-500">Active</span>
        </div>
      </div>
      <div className="absolute bottom-0 right-0 flex items-end gap-2 p-4">
        {accounts.map((acc) => (
          <div key={acc.label} className="flex flex-col items-center gap-1">
            <div className="w-6 h-[72px] bg-white/5 rounded-sm overflow-hidden flex items-end">
              <div
                className="w-full rounded-t-sm"
                style={{
                  height: `${acc.value}%`,
                  background: 'linear-gradient(to top, #064B34, #10BC83)',
                }}
              />
            </div>
            <span className="text-[9px] text-gfx-neutral-300">{acc.label}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

// src/lib/components/dashboard/LiveAccountsCard.svelte
<script>
  /** @type {{ accounts?: Array<{label: string, value: number}>, totalBalance?: string }} */
  let {
    accounts = [
      { label: 'L#1644545', value: 85 },
      { label: 'L#1644545', value: 90 },
      { label: 'L#1644545', value: 45 },
    ],
    totalBalance = '$90.254,58'
  } = $props();
</script>

<div class="relative overflow-hidden bg-white/5 rounded-2xl shadow-[0px_4.64px_23.2px_rgba(0,0,0,0.2),inset_0px_1.16px_0px_1.16px_rgba(255,255,255,0.04)] outline outline-1 outline-offset-[-1.16px] outline-white/5 backdrop-blur-xl h-full">
  <div class="absolute top-0 left-[10%] right-[10%] h-px bg-gradient-to-r from-white/0 via-white/10 to-white/0"></div>
  <div class="absolute w-[493px] h-72 -left-[72px] top-[105px] rounded-full blur-[157px] pointer-events-none" style="background: rgba(16, 64, 48, 0.6)" aria-hidden="true"></div>

  <div class="relative z-10 flex flex-col h-full">
    <!-- Header row: full width -->
    <div class="flex justify-between items-center px-5 pt-5">
      <div class="text-sm font-normal font-acid leading-5 text-gfx-neutral-500">Live Accounts</div>
      <div class="px-2.5 py-1.5 bg-teal-700/25 rounded-[20.83px] outline outline-1 outline-offset-[-1px] outline-neutral-700 backdrop-blur-xs inline-flex justify-start items-start gap-1.5">
        <span class="text-white text-xs font-normal font-acid leading-5">{totalBalance}</span>
      </div>
    </div>

    <!-- Body: text left + charts right -->
    <div class="flex flex-1">
      <div class="w-1/2 flex flex-col px-5 pb-4">
        <div class="flex items-center gap-2 mt-2">
          <span class="text-4xl text-white font-normal font-acid">3</span>
          <span class="text-sm font-normal font-acid leading-5 text-gfx-green-500">Active</span>
        </div>
      </div>

      <!-- Right: bar charts (50%) -->
      <div class="w-1/2 flex items-end gap-2 px-4 pb-4">
      {#each accounts as account}
        <div class="flex-1 flex flex-col items-center gap-1.5">
          <div class="w-full relative rounded-md bg-white/5 overflow-hidden h-[72px]">
            <div
              class="absolute bottom-0 left-0 right-0 rounded-md"
              style="height: {account.value}%; background: linear-gradient(to top, #064B34, #10BC83);"
            ></div>
          </div>
          <span class="text-[9px] font-acid text-gfx-neutral-500 whitespace-nowrap">{account.label}</span>
        </div>
      {/each}
      </div>
    </div>
  </div>
</div>
