// src/components/dashboard/PortfolioEquity.tsx
import { GlassCard, PeriodPill } from '@/components/ui'
import { PortfolioChart } from '@/components/charts/PortfolioChart'

export function PortfolioEquity() {
  return (
    <GlassCard variant="heavy" divider="green" rounded="18px" className="h-full overflow-hidden">
      <div className="absolute w-[400px] h-[200px] -left-[120px] -top-[80px] rounded-full pointer-events-none" style={{ background: '#104030', filter: 'blur(120px)' }} aria-hidden="true" />
      <div className="absolute w-[300px] h-[150px] left-1/2 -translate-x-1/2 -bottom-[80px] rounded-full pointer-events-none" style={{ background: '#104030', filter: 'blur(100px)' }} aria-hidden="true" />
      <div className="relative z-10 p-4 sm:p-6 flex flex-col h-full">
        <div className="flex items-start justify-between mb-4 flex-wrap gap-3">
          <div>
            <h2 className="text-tab uppercase tracking-[2.32px] text-gfx-neutral-300 mb-2">PORTFOLIO EQUITY</h2>
            <div className="flex flex-row items-center gap-3">
              <p className="text-2xl sm:text-3xl text-white">$17,897.30</p>
              <p className="text-sm text-gfx-green-500">+$6,437.21 (56.1%)</p>
            </div>
          </div>
          <PeriodPill />
        </div>
        <PortfolioChart />
      </div>
    </GlassCard>
  )
}

// src/lib/components/dashboard/PortfolioEquity.svelte
<script>
  import { GlassCard, PeriodPill } from '$components/ui';
  import PortfolioChart from '$components/charts/PortfolioChart.svelte';
</script>

<GlassCard variant="heavy" divider="green" rounded="18px" className="h-full overflow-hidden">
  <div class="absolute w-[400px] h-[250px] -left-[100px] -top-[80px] rounded-full blur-[140px] pointer-events-none" style="background: #104030" aria-hidden="true"></div>
  <div class="absolute w-[350px] h-[200px] left-1/2 -translate-x-1/2 -bottom-[60px] rounded-full blur-[130px] pointer-events-none" style="background: #104030" aria-hidden="true"></div>
  <div class="relative z-10 p-5 flex flex-col h-full">
    <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-4 gap-3">
      <div>
        <div class="text-body2 uppercase tracking-[2.32px] font-normal text-gfx-neutral-500 mb-2">Portfolio Equity</div>
        <div class="flex items-baseline gap-3">
          <span class="text-[22px] sm:text-[28px] text-white font-normal">$17,897.30</span>
          <span class="text-gfx-green-500 text-body2 font-normal">+$6,437.21 (56.1%)</span>
        </div>
      </div>

      <PeriodPill />
    </div>

    <div class="flex-1 min-h-[200px]">
      <PortfolioChart />
    </div>
  </div>
</GlassCard>
