// src/components/dashboard/QuickActions.tsx
import { GlassCard, ActionItem } from '@/components/ui'
import { ServerTime } from './ServerTime'
import { DepositIcon, UserIcon, BookIcon, MarketNewsIcon } from '@/components/icons'
import { quickActions } from '@/data/quick-actions'
import type { ReactNode } from 'react'

const iconRender: Record<string, ReactNode> = {
  deposit: <DepositIcon size={24} color="white" />,
  user: <UserIcon size={24} color="white" />,
  chart: <MarketNewsIcon size={21} color="white" />,
  book: <BookIcon size={24} color="white" />,
}

export function QuickActions() {
  return (
    <GlassCard variant="heavy" divider="white" rounded="20px" className="h-full">
      <div className="absolute w-[250px] h-[120px] right-[-40px] top-[-20px] rounded-full pointer-events-none" style={{ background: '#104030', filter: 'blur(100px)' }} aria-hidden="true" />
      <div className="relative z-10 p-4 sm:p-6">
        <h2 className="text-btn text-white mb-4 font-normal">Quick Actions</h2>
        <div className="flex flex-col gap-3">
          {quickActions.map((action) => (
            <ActionItem
              key={action.title}
              title={action.title}
              subtitle={action.subtitle}
              icon={iconRender[action.icon] || <span>?</span>}
            />
          ))}
        </div>
        <ServerTime />
      </div>
    </GlassCard>
  )
}

// src/lib/components/dashboard/QuickActions.svelte
<script>
  import { GlassCard, ActionItem } from '$components/ui';
  import ServerTime from '$components/dashboard/ServerTime.svelte';
  import { DepositIcon, UserIcon, BookIcon } from '$icons';
  import { quickActions } from '$data/quick-actions.js';

  const iconMap = {
    deposit: DepositIcon,
    user: UserIcon,
    book: BookIcon,
  };
</script>

<GlassCard variant="heavy" divider="white" rounded="20px" className="h-full">
  <div class="absolute w-[300px] h-[200px] -right-[60px] -top-[60px] rounded-full blur-[120px] pointer-events-none" style="background: #104030" aria-hidden="true"></div>
  <div class="relative z-10 p-4 flex-1 flex flex-col">
    <div class="text-[16px] font-normal text-white mb-4">Quick Actions</div>

    <div class="flex flex-col gap-2 flex-1">
      {#each quickActions as action}
        {@const IconComponent = iconMap[action.icon]}
        <ActionItem title={action.title} subtitle={action.subtitle}>
          {#snippet icon()}
            {#if action.icon === 'chart'}
              <span class="text-lg">📊</span>
            {:else if IconComponent}
              <IconComponent />
            {/if}
          {/snippet}
        </ActionItem>
      {/each}
    </div>

    <ServerTime />
  </div>
</GlassCard>
