// src/components/charts/AreaChart.tsx
import { useEffect, useRef } from 'react'

interface AreaChartProps {
  color?: string
  className?: string
}

export function AreaChart({ color = '#10BC83', className = 'h-14' }: AreaChartProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const chartRef = useRef<any>(null)

  useEffect(() => {
    let mounted = true
    async function init() {
      const { Chart, registerables } = await import('chart.js')
      Chart.register(...registerables)
      if (!mounted || !canvasRef.current) return

      const ctx = canvasRef.current.getContext('2d')!
      const gradient = ctx.createLinearGradient(0, 0, 0, canvasRef.current.height)
      gradient.addColorStop(0, color + '4D')
      gradient.addColorStop(1, color + '00')

      chartRef.current = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['', '', '', '', '', '', ''],
          datasets: [{
            data: [10, 15, 12, 25, 22, 35, 50],
            fill: true, backgroundColor: gradient,
            borderColor: color, borderWidth: 1.5, tension: 0.4,
            pointRadius: [0, 0, 0, 0, 4, 0, 0],
            pointBackgroundColor: color,
          }],
        },
        options: {
          responsive: true, maintainAspectRatio: false,
          plugins: { legend: { display: false }, tooltip: { enabled: false } },
          scales: { x: { display: false }, y: { display: false } },
        },
      })
    }
    init()
    return () => { mounted = false; chartRef.current?.destroy() }
  }, [color])

  return <div className={className}><canvas ref={canvasRef} className="w-full h-full" aria-label="Trend chart" role="img" /></div>
}

// src/lib/components/charts/AreaChart.svelte
<script>
  import { browser } from '$app/environment';

  /** @type {{ color?: string, className?: string }} */
  let { color = '#10BC83', className = 'h-14' } = $props();

  let canvasEl = $state(null);

  $effect(() => {
    if (!browser || !canvasEl) return;

    let destroyed = false;
    let instance;

    import('chart.js').then(({ Chart, registerables }) => {
      if (destroyed) return;
      Chart.register(...registerables);

      const ctx = canvasEl.getContext('2d');
      const rect = canvasEl.parentElement.getBoundingClientRect();
      const gradient = ctx.createLinearGradient(0, 0, 0, rect.height);
      gradient.addColorStop(0, color + '4D');
      gradient.addColorStop(1, color + '00');

      instance = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['', '', '', '', '', '', ''],
          datasets: [{
            data: [10, 15, 12, 25, 22, 35, 50],
            borderColor: color,
            backgroundColor: gradient,
            borderWidth: 2,
            fill: true,
            tension: 0.4,
            pointRadius: 0,
            pointHoverRadius: 3,
            pointHoverBackgroundColor: color,
          }]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: { display: false },
            tooltip: {
              backgroundColor: 'rgba(0,0,0,0.8)',
              bodyColor: '#fff',
              borderColor: 'rgba(255,255,255,0.1)',
              borderWidth: 1,
              displayColors: false,
            }
          },
          scales: {
            x: { display: false },
            y: { display: false }
          }
        }
      });
    });

    return () => {
      destroyed = true;
      if (instance) instance.destroy();
    };
  });
</script>

<div class={className} role="img" aria-label="Area trend chart">
  <canvas bind:this={canvasEl}></canvas>
</div>
