// src/components/ui/PortfolioChart.tsx
const DEFAULT_SERIES = [150, 160, 145, 170, 190, 175, 200, 220, 210, 240, 260, 250, 280, 305, 290, 270, 260, 250, 240, 260, 280, 300, 290, 270, 260, 245, 230, 250, 270, 260]

interface PortfolioChartProps {
  data?: number[]
  yLabels?: string[]
  className?: string
}

export function PortfolioChart({
  data = DEFAULT_SERIES,
  yLabels = ['$305', '$253', '$202', '$150', '$98'],
  className = '',
}: PortfolioChartProps) {
  const w = 1100
  const h = 290
  const max = Math.max(...data)
  const min = Math.min(...data)
  const range = max - min || 1
  const step = w / (data.length - 1)
  const points = data.map((v, i) => [i * step, h - ((v - min) / range) * h * 0.85 - h * 0.05])
  const pathD = points.map((p, i) => `${i === 0 ? 'M' : 'L'}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(' ')
  const areaD = `${pathD} L${w},${h} L0,${h} Z`
  const marker = points[Math.min(20, points.length - 1)]

  return (
    <div className={`relative w-full ${className}`}>
      <div className="flex">
        <div className="flex flex-col justify-between pr-4 py-1" style={{ height: `${h}px` }}>
          {yLabels.map(label => (
            <span key={label} className="text-gfx-neutral-400 text-xs font-acid">{label}</span>
          ))}
        </div>
        <div className="flex-1">
          <svg width="100%" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" style={{ height: `${h}px` }}>
            <defs>
              <linearGradient id="portfolioGrad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor="#10BC83" stopOpacity="0.2" />
                <stop offset="100%" stopColor="#10BC83" stopOpacity="0" />
              </linearGradient>
              <linearGradient id="lineGrad" x1="0" y1="0" x2="1" y2="0">
                <stop offset="0%" stopColor="#10BC83" stopOpacity="0.3" />
                <stop offset="50%" stopColor="#10BC83" stopOpacity="1" />
                <stop offset="100%" stopColor="#10BC83" stopOpacity="0.5" />
              </linearGradient>
            </defs>
            {[0.15, 0.38, 0.6, 0.83].map((y, i) => (
              <line key={i} x1="0" y1={h * y} x2={w} y2={h * y} stroke="#1a2e26" strokeWidth="0.5" strokeDasharray="4 4" />
            ))}
            <path d={areaD} fill="url(#portfolioGrad)" />
            <path d={pathD} stroke="url(#lineGrad)" strokeWidth="2" fill="none" />
            <circle cx={marker[0]} cy={marker[1]} r="12" fill="#10BC83" opacity="0.15" />
            <circle cx={marker[0]} cy={marker[1]} r="4" fill="#10BC83" />
            <line x1={marker[0]} y1={marker[1] + 16} x2={marker[0]} y2={h} stroke="#10BC83" strokeWidth="0.5" strokeDasharray="3 3" opacity="0.4" />
          </svg>
        </div>
      </div>
    </div>
  )
}

// src/lib/components/charts/PortfolioChart.svelte
<script>
  /** @type {{ yLabels?: string[] }} */
  let { yLabels = ['$305','$253','$202','$150','$98'] } = $props();
</script>

<div class="relative h-[150px]">
  <div class="absolute left-0 top-0 bottom-0 flex flex-col justify-between text-[10px] text-gfx-neutral-500 pr-3">
    {#each yLabels as label}
      <span>{label}</span>
    {/each}
  </div>
  <div class="ml-10 h-full relative">
    <div class="absolute inset-0 flex flex-col justify-between">
      {#each yLabels as _}
        <div class="border-b border-[rgba(255,255,255,0.04)]"></div>
      {/each}
    </div>
    <svg width="100%" height="100%" viewBox="0 0 900 280" preserveAspectRatio="none" class="relative z-10">
      <defs>
        <linearGradient id="portfolioGrad" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stop-color="#10BC83" stop-opacity="0.25"/>
          <stop offset="100%" stop-color="#10BC83" stop-opacity="0"/>
        </linearGradient>
      </defs>
      <path d="M0,250 C50,248 80,240 120,230 C160,220 200,210 240,195 C280,180 320,170 360,155 C400,140 440,125 480,115 C520,105 560,100 600,90 C640,80 680,70 720,55 C760,42 800,35 850,28 L900,20 V280 H0 Z" fill="url(#portfolioGrad)"/>
      <path d="M0,250 C50,248 80,240 120,230 C160,220 200,210 240,195 C280,180 320,170 360,155 C400,140 440,125 480,115 C520,105 560,100 600,90 C640,80 680,70 720,55 C760,42 800,35 850,28 L900,20" fill="none" stroke="#10BC83" stroke-width="2"/>
      <circle cx="720" cy="55" r="5" fill="#10BC83" stroke="#000" stroke-width="2"/>
    </svg>
    <div class="absolute top-0 bottom-0 border-l border-dashed border-[rgba(16,188,131,0.3)]" style="left: 80%;"></div>
  </div>
</div>
