// src/lib/components/charts/CandlestickChart.svelte
<script>
  import { browser } from '$app/environment';

  /** @type {{ data: Array<{wickTop: number, body: number, wickBottom: number, bullish: boolean}>, className?: string }} */
  let { data = [], className = 'h-14' } = $props();

  let canvasEl = $state(null);

  $effect(() => {
    if (!browser || !canvasEl || data.length === 0) return;

    let destroyed = false;
    let instance;

    import('chart.js').then(({ Chart, registerables }) => {
      if (destroyed) return;
      Chart.register(...registerables);

      const barData = data.map(c => c.body);
      const colors = data.map(c => c.bullish ? '#10BC83' : '#ff717e');

      instance = new Chart(canvasEl.getContext('2d'), {
        type: 'bar',
        data: {
          labels: data.map(() => ''),
          datasets: [{
            data: barData,
            backgroundColor: colors,
            borderRadius: 2,
            borderSkipped: false,
            barPercentage: 0.5,
          }]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: { display: false },
            tooltip: {
              backgroundColor: 'rgba(0,0,0,0.8)',
              bodyColor: '#fff',
              borderColor: 'rgba(255,255,255,0.1)',
              borderWidth: 1,
              displayColors: false,
            }
          },
          scales: {
            x: { display: false },
            y: { display: false }
          }
        }
      });
    });

    return () => {
      destroyed = true;
      if (instance) instance.destroy();
    };
  });
</script>

<div class={className} role="img" aria-label="Candlestick chart">
  <canvas bind:this={canvasEl}></canvas>
</div>

// src/components/charts/CandlestickChart.tsx
import { useEffect, useRef } from 'react'

interface CandleData {
  wickTop: number
  body: number
  wickBottom: number
  bullish: boolean
}

interface CandlestickChartProps {
  data: CandleData[]
  className?: string
}

export function CandlestickChart({ data, className = 'h-14' }: CandlestickChartProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const chartRef = useRef<any>(null)

  useEffect(() => {
    let mounted = true
    async function init() {
      const { Chart, registerables } = await import('chart.js')
      Chart.register(...registerables)
      if (!mounted || !canvasRef.current) return

      chartRef.current = new Chart(canvasRef.current, {
        type: 'bar',
        data: {
          labels: data.map(() => ''),
          datasets: [{
            data: data.map(d => d.body),
            backgroundColor: data.map(d => d.bullish ? '#10BC83' : '#ff717e'),
            borderSkipped: false,
            barPercentage: 0.5,
          }],
        },
        options: {
          responsive: true, maintainAspectRatio: false,
          plugins: { legend: { display: false }, tooltip: { enabled: false } },
          scales: { x: { display: false }, y: { display: false } },
        },
      })
    }
    init()
    return () => { mounted = false; chartRef.current?.destroy() }
  }, [data])

  return <div className={className}><canvas ref={canvasRef} className="w-full h-full" aria-label="Candlestick chart" role="img" /></div>
}
