// src/lib/components/charts/MiniBarChart.svelte
<script>
  import { browser } from '$app/environment';

  /** @type {{ data: Array<{value: number, label?: string}>, className?: string }} */
  let { data = [], className = 'h-14' } = $props();

  let canvasEl = $state(null);

  $effect(() => {
    if (!browser || !canvasEl || data.length === 0) return;

    let destroyed = false;
    let instance;

    import('chart.js').then(({ Chart, registerables }) => {
      if (destroyed) return;
      Chart.register(...registerables);

      instance = new Chart(canvasEl.getContext('2d'), {
        type: 'bar',
        data: {
          labels: data.map((d) => d.label || ''),
          datasets: [{
            data: data.map(d => d.value),
            backgroundColor: (ctx) => {
              const chart = ctx.chart;
              const { ctx: c, chartArea } = chart;
              if (!chartArea) return '#10BC83';
              const g = c.createLinearGradient(0, chartArea.bottom, 0, chartArea.top);
              g.addColorStop(0, '#064B34');
              g.addColorStop(1, '#10BC83');
              return g;
            },
            borderRadius: { topLeft: 4, topRight: 4 },
            borderSkipped: false,
          }]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: { display: false },
            tooltip: {
              backgroundColor: 'rgba(0,0,0,0.8)',
              bodyColor: '#fff',
              borderColor: 'rgba(255,255,255,0.1)',
              borderWidth: 1,
              displayColors: false,
              callbacks: {
                label: (ctx) => `$${ctx.parsed.y.toLocaleString()}`
              }
            }
          },
          scales: {
            x: {
              grid: { display: false },
              ticks: { color: '#606060', font: { size: 9 } },
              border: { display: false }
            },
            y: { display: false }
          }
        }
      });
    });

    return () => {
      destroyed = true;
      if (instance) instance.destroy();
    };
  });
</script>

<div class={className} role="img" aria-label="Bar chart">
  <canvas bind:this={canvasEl}></canvas>
</div>

// src/components/charts/MiniBarChart.tsx
import { useEffect, useRef } from 'react'

interface MiniBarChartProps {
  data: number[]
  className?: string
}

export function MiniBarChart({ data, className = 'h-14' }: MiniBarChartProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const chartRef = useRef<any>(null)

  useEffect(() => {
    let mounted = true
    async function init() {
      const { Chart, registerables } = await import('chart.js')
      Chart.register(...registerables)
      if (!mounted || !canvasRef.current) return

      const ctx = canvasRef.current.getContext('2d')!
      const gradient = ctx.createLinearGradient(0, canvasRef.current.height, 0, 0)
      gradient.addColorStop(0, '#064B34')
      gradient.addColorStop(1, '#10BC83')

      chartRef.current = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: data.map(() => ''),
          datasets: [{ data, backgroundColor: gradient, borderRadius: { topLeft: 4, topRight: 4 }, borderSkipped: false }],
        },
        options: {
          responsive: true, maintainAspectRatio: false,
          plugins: { legend: { display: false }, tooltip: {
            backgroundColor: '#1a1a1a', bodyColor: '#fff', displayColors: false,
            callbacks: { label: (ctx) => `$${(ctx.parsed.y ?? 0).toLocaleString()}` },
          }},
          scales: {
            x: { grid: { display: false }, ticks: { color: '#606060', font: { size: 9 } } },
            y: { display: false },
          },
        },
      })
    }
    init()
    return () => { mounted = false; chartRef.current?.destroy() }
  }, [data])

  return <div className={className}><canvas ref={canvasRef} className="w-full h-full" aria-label="Bar chart" role="img" /></div>
}
