// src/components/ui/Breadcrumb.tsx
import { HomeIcon } from '@/components/icons'

interface BreadcrumbItem {
  label: string
  href?: string
  current?: boolean
}

interface BreadcrumbProps {
  items: BreadcrumbItem[]
}

export function Breadcrumb({ items }: BreadcrumbProps) {
  return (
    <nav aria-label="Breadcrumb">
      <ol className="flex items-center gap-4 text-body2" style={{ color: '#606060' }}>
        <li><HomeIcon size={21} color="#606060" /></li>
        {items.map((item, i) => (
          <li key={i} className="flex items-center gap-4">
            <span aria-hidden="true">/</span>
            {item.current ? (
              <span aria-current="page">{item.label}</span>
            ) : (
              <a href={item.href || '#'} className="hover:text-white transition-colors">{item.label}</a>
            )}
          </li>
        ))}
      </ol>
    </nav>
  )
}

// src/lib/components/ui/Breadcrumb.svelte
<script>
  import { HomeIcon } from '$icons';

  /** @type {{ items: Array<{ label: string, href?: string, current?: boolean }> }} */
  let { items } = $props();
</script>

<nav aria-label="Breadcrumb">
  <ol class="flex items-center gap-4 text-body2" style="color: #606060">
    <li class="flex items-center">
      <HomeIcon />
    </li>

    {#each items as item, i}
      {#if i > 0}
        <span style="color: #606060">/</span>
      {/if}
      <li class="flex items-center">
        {#if item.current}
          <span class="font-normal" style="color: #606060">{item.label}</span>
        {:else}
          <a href={item.href || '#'} class="hover:opacity-80 transition-colors" style="color: #606060">
            {item.label}
          </a>
        {/if}
      </li>
    {/each}
  </ol>
</nav>
