// src/components/ui/ModeToggle.tsx
import { useState, useRef, useLayoutEffect } from 'react'
import type { ReactNode } from 'react'
import gsap from 'gsap'
import './ModeToggle.css'

const OPTION_ICONS: Record<string, (color: string) => ReactNode> = {
  Client: (color) => (
    <svg width="16" height="16" viewBox="0 0 18 18" fill="none">
      <circle cx="9" cy="4.5" r="3" fill={color} />
      <ellipse cx="9" cy="12.75" rx="5.25" ry="3" fill={color} />
    </svg>
  ),
  Partner: (color) => (
    <svg width="16" height="16" viewBox="0 0 20 18" fill="none">
      <circle cx="7" cy="4.5" r="2.8" fill={color} />
      <ellipse cx="7" cy="12.5" rx="4.5" ry="2.8" fill={color} />
      <circle cx="14" cy="5.5" r="2.2" fill={color} opacity="0.55" />
      <ellipse cx="14" cy="13" rx="3.5" ry="2.2" fill={color} opacity="0.55" />
    </svg>
  ),
}

interface ModeToggleProps {
  options?: string[]
  defaultIndex?: number
  activeIndex?: number
  onChange?: (index: number) => void
}

export function ModeToggle({ options = ['Client', 'Partner'], defaultIndex = 0, activeIndex, onChange }: ModeToggleProps) {
  const [internalActive, setInternalActive] = useState(defaultIndex)
  const active = activeIndex ?? internalActive
  const indicatorRef = useRef<HTMLDivElement>(null)
  const isFirst = useRef(true)

  useLayoutEffect(() => {
    if (!indicatorRef.current) return

    const xPct = active * 100

    if (isFirst.current) {
      gsap.set(indicatorRef.current, { xPercent: xPct })
      isFirst.current = false
    } else {
      gsap.to(indicatorRef.current, {
        xPercent: xPct,
        duration: 0.4,
        ease: 'power2.inOut',
      })
    }
  }, [active])

  return (
    <div className="mode-toggle" role="group" aria-label="Mode selection">
      <div
        ref={indicatorRef}
        className="mode-indicator"
        style={{ width: `${100 / options.length}%` }} /* dynamic */
        aria-hidden="true"
      >
        <div className="glow-emerald-mode" aria-hidden="true" />
        <div className="fading-border" aria-hidden="true" />
        <svg className="absolute" style={{ left: '78%', top: '60%' }} width="3" height="3" viewBox="0 0 3 3" fill="none" aria-hidden="true">
          <circle cx="1.5" cy="1.5" r="0.5" fill="white" filter="url(#mt_sparkle)" />
        </svg>
        <svg className="absolute opacity-50" style={{ left: '67%', top: '72%' }} width="3" height="3" viewBox="0 0 3 3" fill="none" aria-hidden="true">
          <circle cx="1.5" cy="1.5" r="0.5" fill="white" filter="url(#mt_sparkle)" />
        </svg>
        <svg className="absolute" style={{ left: '40%', top: '10%' }} width="3" height="3" viewBox="0 0 3 3" fill="none" aria-hidden="true">
          <circle cx="1.5" cy="1.5" r="0.5" fill="#ACACAC" filter="url(#mt_sparkle)" />
        </svg>
        <svg className="absolute" style={{ left: '55%', top: '80%' }} width="3" height="3" viewBox="0 0 3 3" fill="none" aria-hidden="true">
          <circle cx="1.5" cy="1.5" r="0.5" fill="#ACACAC" filter="url(#mt_sparkle)" />
        </svg>
        <svg className="absolute" style={{ left: '69%', top: '18%' }} width="3" height="3" viewBox="0 0 3 3" fill="none" aria-hidden="true">
          <circle cx="1.5" cy="1.5" r="0.5" fill="#ACACAC" filter="url(#mt_sparkle)" />
        </svg>
        <svg className="absolute" style={{ left: '39%', top: '73%' }} width="3" height="3" viewBox="0 0 3 3" fill="none" aria-hidden="true">
          <circle cx="1.5" cy="1.5" r="0.5" fill="#ACACAC" filter="url(#mt_sparkle)" />
        </svg>
        <svg className="absolute" style={{ left: '26%', top: '25%' }} width="3" height="3" viewBox="0 0 3 3" fill="none" aria-hidden="true">
          <circle cx="1.5" cy="1.5" r="0.5" fill="#8C8C8C" filter="url(#mt_sparkle)" />
        </svg>
        <svg className="absolute" style={{ left: '10%', top: '64%' }} width="4" height="3" viewBox="0 0 4 3" fill="none" aria-hidden="true">
          <ellipse cx="2" cy="1.5" rx="1" ry="0.5" fill="#8C8C8C" filter="url(#mt_sparkle)" />
        </svg>
        <svg className="absolute w-0 h-0" aria-hidden="true">
          <defs>
            <filter id="mt_sparkle" x="-50%" y="-50%" width="200%" height="200%" colorInterpolationFilters="sRGB">
              <feGaussianBlur stdDeviation="0.5" />
            </filter>
          </defs>
        </svg>
      </div>
      {options.map((option, i) => {
        const isActive = active === i
        const iconFn = OPTION_ICONS[option]
        return (
          <button
            key={option}
            className={isActive ? 'active' : ''}
            onClick={() => { setInternalActive(i); onChange?.(i) }}
            aria-pressed={isActive}
          >
            {iconFn && <span className="btn-icon">{iconFn(isActive ? '#fff' : '#606060')}</span>}
            <span className="btn-label">{option}</span>
          </button>
        )
      })}
    </div>
  )
}

// src/lib/components/ui/ModeToggle.svelte
<script>
  /** @type {{ options?: string[], activeIndex?: number }} */
  let { options = ['Client', 'Partner'], activeIndex = 0 } = $props();

  let active = $state(activeIndex);
</script>

<div class="mode-toggle" role="group" aria-label="Mode selection">
  {#each options as option, i}
    <button
      class:active={active === i}
      onclick={() => active = i}
      aria-pressed={active === i}
    >
      <span class="btn-label">{option}</span>
      {#if active === i}
        <div class="glow-emerald" aria-hidden="true"></div>
        <div class="star star-1" aria-hidden="true"></div>
        <div class="star star-2" aria-hidden="true"></div>
        <div class="star star-3" aria-hidden="true"></div>
        <div class="star star-4" aria-hidden="true"></div>
        <div class="star star-5" aria-hidden="true"></div>
        <div class="star star-6" aria-hidden="true"></div>
        <div class="star star-7" aria-hidden="true"></div>
        <div class="star star-8" aria-hidden="true"></div>
      {/if}
    </button>
  {/each}
</div>

<style>
  .mode-toggle {
    width: 100%;
    height: 44px;
    border-radius: 60px;
    background: rgba(255,255,255,0.05);
    display: flex;
    position: relative;
    overflow: hidden;
  }
  .mode-toggle button {
    flex: 1;
    border: none;
    background: transparent;
    color: #606060;
    font-size: 16px;
    font-weight: 500;
    cursor: pointer;
    z-index: 1;
    border-radius: 60px;
    transition: all 0.3s;
    position: relative;
    overflow: hidden;
  }
  .mode-toggle button:focus-visible {
    outline: 2px solid #10BC83;
    outline-offset: -2px;
  }
  .mode-toggle button.active {
    background: rgba(20,184,166,0.2);
    border: 0.5px solid #14b8a6;
    color: #fff;
    font-weight: 500;
  }
  .btn-label {
    position: relative;
    z-index: 2;
  }
  .glow-emerald {
    position: absolute;
    width: 98px;
    height: 45px;
    left: 28px;
    bottom: -20px;
    background: #55FFC7;
    border-radius: 50%;
    filter: blur(20px);
    pointer-events: none;
    opacity: 0.3;
  }
  .star {
    position: absolute;
    width: 1px;
    height: 1px;
    border-radius: 50%;
    pointer-events: none;
    z-index: 1;
  }
  .star-1 { left: 104px; top: 26px; background: white; filter: blur(0.5px); }
  .star-2 { left: 89px; top: 31px; background: white; opacity: 0.5; filter: blur(0.5px); }
  .star-3 { left: 53px; top: 4px; background: #acacac; filter: blur(0.5px); }
  .star-4 { left: 74px; top: 35px; background: #acacac; filter: blur(0.5px); }
  .star-5 { left: 92px; top: 8px; background: #acacac; filter: blur(0.5px); }
  .star-6 { left: 52px; top: 32px; background: #acacac; filter: blur(0.5px); }
  .star-7 { left: 35px; top: 11px; background: #8c8c8c; filter: blur(0.5px); }
  .star-8 { left: 13px; top: 28px; background: #8c8c8c; filter: blur(0.5px); }
</style>
