// src/lib/components/ui/ActionItem.svelte
<script>
  /** @type {{ title: string, subtitle: string, icon: import('svelte').Snippet }} */
  let { title, subtitle, icon } = $props();
</script>

<button class="w-full h-24 relative rounded-2xl outline outline-[1.25px] outline-offset-[-1.25px] outline-white/5 flex items-center gap-4 px-5 cursor-pointer transition-all duration-200 hover:bg-white/[0.03] focus-visible:outline-2 focus-visible:outline-gfx-green-500" type="button">
  <div class="size-14 shrink-0 bg-teal-500/5 rounded-xl outline outline-[1.25px] outline-offset-[-1.25px] outline-teal-500/10 flex items-center justify-center">
    {@render icon()}
  </div>
  <div class="text-left">
    <div class="text-white text-base font-normal font-acid leading-6">{title}</div>
    <div class="text-gfx-neutral-300 text-sm font-normal font-acid leading-5">{subtitle}</div>
  </div>
</button>

// src/components/ui/ActionItem.tsx
import type { ReactNode } from 'react'

interface ActionItemProps {
  title: string
  subtitle: string
  icon: ReactNode
}

export function ActionItem({ title, subtitle, icon }: ActionItemProps) {
  return (
    <button className="w-full h-16 xl:h-[68px] 2xl:h-24 rounded-md outline outline-1 outline-white/5 flex items-center gap-3 2xl:gap-4 px-4 2xl:px-5 bg-transparent hover:bg-white/[0.02] transition-colors text-left cursor-pointer">
      <div className="size-10 2xl:size-14 bg-teal-500/5 rounded-md outline outline-1 outline-offset-[-1.25px] outline-teal-500/10 flex items-center justify-center shrink-0">
        {icon}
      </div>
      <div>
        <span className="text-btn text-white block">{title}</span>
        <span className="text-gfx-neutral-300 text-body1 block">{subtitle}</span>
      </div>
    </button>
  )
}
