// src/lib/components/ui/GlassCard.svelte
<script>
  import DividerGlow from './DividerGlow.svelte';

  /** @type {{ variant?: 'light' | 'heavy', divider?: 'white' | 'green' | 'none', rounded?: string, className?: string, children: import('svelte').Snippet }} */
  let { variant = 'light', divider = 'white', rounded = '19px', className = '', children } = $props();
</script>

<div
  class="{variant === 'heavy' ? 'glass-card-heavy' : 'glass-card'} relative {className}"
  style="border-radius: {rounded};"
>
  {#if divider !== 'none'}
    <DividerGlow variant={divider} />
  {/if}
  {@render children()}
</div>

// src/components/ui/GlassCard.tsx
import type { ReactNode } from 'react'
import { DividerGlow } from './DividerGlow'

interface GlassCardProps {
  variant?: 'light' | 'heavy'
  divider?: 'white' | 'green' | 'none'
  rounded?: string
  className?: string
  children: ReactNode
}

export function GlassCard({ variant = 'light', divider = 'white', rounded = '19px', className = '', children }: GlassCardProps) {
  return (
    <div
      className={`${variant === 'heavy' ? 'glass-card-heavy' : 'glass-card'} relative ${className}`}
      style={{ borderRadius: rounded }} /* dynamic */
    >
      {divider !== 'none' && <DividerGlow variant={divider} />}
      {children}
    </div>
  )
}
