// src/lib/components/ui/SearchInput.svelte
<script>
  import { SearchIcon } from '$icons';

  /** @type {{ placeholder?: string, value?: string }} */
  let { placeholder = 'Search for', value = $bindable('') } = $props();
</script>

<div class="relative">
  <div class="absolute left-3 top-1/2 -translate-y-1/2 text-gfx-neutral-500" aria-hidden="true">
    <SearchIcon />
  </div>
  <input
    type="search"
    bind:value
    {placeholder}
    aria-label={placeholder}
    class="bg-transparent border border-gfx-card-border rounded-full pl-9 pr-4 py-2.5 text-body2 text-white placeholder-gfx-neutral-500 outline-none focus:border-gfx-green-500/30 focus-visible:ring-1 focus-visible:ring-gfx-green-500/30 w-[200px]"
  />
</div>

// src/components/ui/SearchInput.tsx
import { SearchIcon } from '@/components/icons'

interface SearchInputProps {
  placeholder?: string
  value?: string
  onChange?: (value: string) => void
}

export function SearchInput({ placeholder = 'Search for', value = '', onChange }: SearchInputProps) {
  return (
    <div className="relative">
      <SearchIcon size={14} color="#A0A0A0" className="absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none" />
      <input
        type="search"
        placeholder={placeholder}
        value={value}
        onChange={(e) => onChange?.(e.target.value)}
        aria-label="Search accounts"
        className="pl-9 pr-4 py-2.5 border border-gfx-card-border rounded-full bg-transparent text-white text-body2 w-[200px] focus:border-gfx-green-500/30 focus:outline-none transition-colors placeholder:text-gfx-neutral-300"
      />
    </div>
  )
}
